# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'index.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(523, 342)
        MainWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        MainWindow.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        MainWindow.setMinimumSize(QtCore.QSize(523, 342))
        MainWindow.setMaximumSize(QtCore.QSize(523, 342))
        MainWindow.setStyleSheet("QProgressBar {\n"
"    border-radius: 10px;\n"
"    text-align: center;\n"
"    background-color: rgb(142, 68, 173);\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    border-radius: 12px;\n"
"\n"
"    margin: 0.5px;\n"
"    background-color: rgb(44, 62, 80);\n"
"}\n"
"QLabel {\n"
"    background-color: transparent;\n"
"    color: rgb(142, 68, 173);\n"
"}\n"
"\n"
"QFrame {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.04, x2:0.985782, y2:0.693182, stop:0 rgba(44, 62, 80, 255), stop:1 rgba(38, 53, 69, 255));\n"
"\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_all = QtWidgets.QFrame(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.frame_all.setFont(font)
        self.frame_all.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_all.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_all.setObjectName("frame_all")
        self.prog = QtWidgets.QProgressBar(self.frame_all)
        self.prog.setGeometry(QtCore.QRect(50, 200, 431, 41))
        self.prog.setProperty("value", 24)
        self.prog.setObjectName("prog")
        self.label = QtWidgets.QLabel(self.frame_all)
        self.label.setGeometry(QtCore.QRect(70, 60, 401, 61))
        font = QtGui.QFont()
        font.setFamily("Raleway Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        self.label.setFont(font)
        self.label.setStyleSheet("    background-color: transparent;\n"
"color:#fff")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame_all)
        self.label_2.setGeometry(QtCore.QRect(70, 130, 401, 51))
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color:  transparent ;\n"
"color: rgb(124, 255, 207)")
        self.label_2.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_all)
        self.label_3.setGeometry(QtCore.QRect(170, 270, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(12)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color:transparent;\n"
"color:#fff")
        self.label_3.setObjectName("label_3")
        self.Qlabel = QtWidgets.QLabel(self.frame_all)
        self.Qlabel.setGeometry(QtCore.QRect(258, 275, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(12)
        font.setBold(True)
        self.Qlabel.setFont(font)
        self.Qlabel.setStyleSheet("#Qlabel{\n"
"\n"
"  background-color:transparent;\n"
"  color:#fff\n"
"}\n"
"\n"
"#Qlabel::hover{\n"
"\n"
"  color:red;\n"
"}\n"
"\n"
"#Qlabel:pressed {\n"
"    border: 4px solid #98c1fe;\n"
"}\n"
"")
        self.Qlabel.setObjectName("Qlabel")
        self.gridLayout.addWidget(self.frame_all, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Image Editor"))
        self.label_2.setText(_translate("MainWindow", "running App ..."))
        self.label_3.setText(_translate("MainWindow", "created by"))
        self.Qlabel.setText(_translate("MainWindow", "imfallah.ir"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
